---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flagger
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
  install:
    crds: Create
    createNamespace: true
  interval: 1m0s
  targetNamespace: flagger-system
  upgrade:
    crds: CreateReplace
  values:
    meshProvider: istio
    prometheus:
      install: false
    metricsServer: "http://prometheus.istio-system.svc.cluster.local:9090"
