apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - app.sample.com
    - app-qa.sample.com
    port:
      number: 80
      name: http
      protocol: HTTP