apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-qa
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: configuration
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/qa
  prune: true
  wait: true
  timeout: 5m0s